### ISSUE TITLE
Browser variations

### ISSUE THREAD

**Issue by sphism** [pascalduez/SassyFilters#6]
Just using sassyfilters today and noticed some differences between chrome, safari and firefox displaying the test page:

http://pascalduez.me/SassyFilters/test/
- Chrome works as expected
- Safari doesn't work at all, the -webkit-filter is overridden by the svg filter, but the svg filter fails.
- Firefox renders things differently, the effects actually look better I think.

Whats the best way to get everything working? Or even better - everything working and looking the same?

**Comment by pascalduez** [comment]
Hi,

About the rendering differences, I had noticed it as well while developing the lib. Not sure exactly why, but I suspect different algorythm to implement the same thing. Which is a bit sad. I don't think there's an easy way to address it. Except maybe UA sniffing.

The issue in Safari might need some attention, if it's just about the order or proper cascade.

Now that `filter` functions are supported in most major browsers and IE vanishing, that lib is making a bit less sense. And I don't think I'll have much time to maintain it actually.

http://caniuse.com/#feat=css-filters

**Comment by sphism** [comment]
Thanks for your quick response, the main part of my work yesterday was to see if I could replicate a custom photoshop filter using several svg filters... in chrome I have it pretty close, and sassyfilters helped a lot.

If it looks different in firefox that's going to be a problem, maybe I'll have to have different settings for that.

Also I used browserstack to test internet explorer and the filters didn't seem to work in 10 or 11... but i seem to remember reading that it should work in earlier versions. I'll do more testing today and figure out a plan.

**Comment by sphism** [comment]
Well I had some success today, I got it working in firefox and safari by altering the output function.

Currently the output order is:
 - -webkit-filter
 - filter: url()
 - -ms-filter
 - filter: old ms filter format

The current web standard is filter: [list of filter functions]

Firefox > 34 no longer supports filter: url() and only supports filter: [list of filter functions]

To fix firefox I added filter: [list of filter functions] to the end of the list (this also might break IE<8 support with it's old filter property???)

Safari wasn't working because filter: url() was overridding -webkit-filter but wasn't actually working, switching the order of those 2 fixed safari, ie

- filter: url()
- -webkit-filter


`@mixin output(
  $output
) {

  //
  // Gecko
  //
  $output: _preprocess-svg-filters($output);

  filter: inline-svg(
            $svgStr: map-get($output, svg),
            $fragment: map-get($output, id)
          );

  //
  // Webkit, Blink
  //
  -webkit-filter: map-get($output, css);


  //
  // IE
  //
  $ie-support: conf(ie-support)
               and map-has-key($output, ie)
               and not empty(map-get($output, ie));

  @if $ie-support {
    $output: _preprocess-ie-filters($output);

    // IE 8+
    -ms-filter: map-get($output, gte-ie8);
    // IE < 8
    filter: map-get($output, lt-ie8);
  }

  //
  // Web standard css.
  //
  filter: map-get($output, css);
}`
